"""
Este arquivo contém a base de dados de livros para o sistema da biblioteca.
Mover os dados para um arquivo separado melhora a organização e legibilidade do código principal.
"""

BASE_LIVROS = [
    # Letra A (10 livros)
    ("A Arte da Guerra", "Sun Tzu", 2015, "Jardim dos Livros", 3),
    ("A Alquimista", "Paulo Coelho", 1988, "Rocco", 5),
    ("As Aventuras de Sherlock Holmes", "Arthur Conan Doyle", 2012, "Zahar", 4),
    ("Amanhecer", "Stephenie Meyer", 2008, "Intrínseca", 2),
    ("A Garota do Lago", "Charlie Donlea", 2017, "Faro Editorial", 3),
    ("Anjos e Demônios", "Dan Brown", 2000, "Arqueiro", 4),
    ("A Culpa é das Estrelas", "John Green", 2012, "Intrínseca", 5),
    ("O Alienista", "Machado de Assis", 1882, "Principis", 3),
    ("A Mão e a Luva", "Machado de Assis", 1874, "Antofágica", 2),
    ("A Metamorfose", "Franz Kafka", 1915, "Companhia das Letras", 4),
    # Letra B (10 livros)
    ("Batalha do Apocalipse", "Eduardo Spohr", 2007, "Verus", 3),
    ("Bilhões e Bilhões", "Carl Sagan", 1997, "Companhia das Letras", 2),
    ("Boxe com Sombra", "Jeferson Tenório", 2013, "Sulina", 4),
    ("Breves Respostas para Grandes Questões", "Stephen Hawking", 2018, "Intrínseca", 3),
    ("Belo Desastre", "Jamie McGuire", 2011, "Verus", 5),
    ("Brida", "Paulo Coelho", 1990, "Rocco", 2),
    ("Bom Dia, Verônica", "Raphael Montes", 2016, "Companhia das Letras", 4),
    ("Beren e Lúthien", "J.R.R. Tolkien", 2017, "HarperCollins", 3),
    ("Belo Mundo, Onde Você Está", "Sally Rooney", 2021, "Companhia das Letras", 2),
    ("Biblioteca da Meia-Noite", "Matt Haig", 2020, "Bertrand", 5),
    # Letra C (10 livros)
    ("Cem Anos de Solidão", "Gabriel García Márquez", 1967, "Record", 4),
    ("O Cortiço", "Aluísio Azevedo", 1890, "Principis", 3),
    ("Crime e Castigo", "Fiódor Dostoiévski", 1866, "Editora 34", 5),
    ("Capitães da Areia", "Jorge Amado", 1937, "Companhia das Letras", 4),
    ("Como Eu Era Antes de Você", "Jojo Moyes", 2012, "Intrínseca", 3),
    ("O Código Da Vinci", "Dan Brown", 2003, "Arqueiro", 5),
    ("Corte de Espinhos e Rosas", "Sarah J. Maas", 2015, "Galera", 4),
    ("Conversando com o Serial Killer", "Christopher Berry-Dee", 2019, "Darkside", 2),
    ("Clube da Luta", "Chuck Palahniuk", 1996, "LeYa", 3),
    ("Coraline", "Neil Gaiman", 2002, "Intrínseca", 5),
    # Letra D (10 livros)
    ("Dom Casmurro", "Machado de Assis", 1899, "Antofágica", 5),
    ("Duna", "Frank Herbert", 1965, "Aleph", 4),
    ("Drácula", "Bram Stoker", 1897, "Darkside", 3),
    ("Divergente", "Veronica Roth", 2011, "Rocco", 5),
    ("Deixei Você Ir", "Clare Mackintosh", 2016, "Record", 2),
    ("Do Mil ao Milhão", "Thiago Nigro", 2018, "HarperCollins", 4),
    ("Depois de Você", "Jojo Moyes", 2015, "Intrínseca", 3),
    ("Daisy Jones and The Six", "Taylor Jenkins Reid", 2019, "Paralela", 5),
    ("Diário de um Banana", "Jeff Kinney", 2007, "VR Editora", 4),
    ("Doutor Sono", "Stephen King", 2013, "Suma", 2),
    # Letra E (10 livros)
    ("Ensaio sobre a Cegueira", "José Saramago", 1995, "Companhia das Letras", 4),
    ("Eu, Robô", "Isaac Asimov", 1950, "Aleph", 3),
    ("Extraordinário", "R.J. Palacio", 2012, "Intrínseca", 5),
    ("E Não Sobrou Nenhum", "Agatha Christie", 1939, "HarperCollins", 4),
    ("Eclipse", "Stephenie Meyer", 2007, "Intrínseca", 2),
    ("É Assim que Acaba", "Colleen Hoover", 2016, "Galera Record", 5),
    ("Eleanor & Park", "Rainbow Rowell", 2013, "Novo Século", 3),
    ("O Exorcista", "William Peter Blatty", 1971, "HarperCollins", 2),
    ("Estudos sobre o Histerismo", "Sigmund Freud", 1895, "L&PM", 4),
    ("Entrevista com o Vampiro", "Anne Rice", 1976, "Rocco", 3),
    # Letra F (10 livros)
    ("Fahrenheit 451", "Ray Bradbury", 1953, "Biblioteca Azul", 4),
    ("Frankenstein", "Mary Shelley", 1818, "Zahar", 3),
    ("Filhos de Duna", "Frank Herbert", 1976, "Aleph", 2),
    ("Fique Comigo", "Ayobami Adebayo", 2017, "HarperCollins", 4),
    ("Felicidade Clandestina", "Clarice Lispector", 1971, "Rocco", 3),
    ("Festim dos Corvos", "George R. R. Martin", 2005, "LeYa", 5),
    ("Flores para Algernon", "Daniel Keyes", 1959, "Aleph", 4),
    ("Fundações", "Isaac Asimov", 1951, "Aleph", 3),
    ("Fazendo Meu Filme", "Paula Pimenta", 2008, "Gutenberg", 5),
    ("Forrest Gump", "Winston Groom", 1986, "Aleph", 2),
    # Letra G (10 livros)
    ("O Grande Gatsby", "F. Scott Fitzgerald", 1925, "Principis", 4),
    ("Grande Sertão: Veredas", "João Guimarães Rosa", 1956, "Companhia das Letras", 3),
    ("Guerra e Paz", "Liev Tolstói", 1869, "Cosac Naify", 5),
    ("O Guia do Mochileiro das Galáxias", "Douglas Adams", 1979, "Arqueiro", 4),
    ("Garota Exemplar", "Gillian Flynn", 2012, "Intrínseca", 3),
    ("Guerra dos Tronos", "George R. R. Martin", 1996, "LeYa", 5),
    ("Gatilho", "Arthur C. Clarke", 2000, "Aleph", 2),
    ("Geração de Valor", "Flávio Augusto da Silva", 2014, "Sextante", 4),
    ("O Gene Egoísta", "Richard Dawkins", 1976, "Companhia das Letras", 3),
    ("Gótico Mexicano", "Silvia Moreno-Garcia", 2020, "Darkside", 2),
    # Letra H (10 livros)
    ("O Hobbit", "J.R.R. Tolkien", 1937, "HarperCollins", 5),
    ("Harry Potter e a Pedra Filosofal", "J.K. Rowling", 1997, "Rocco", 5),
    ("Holocausto Brasileiro", "Daniela Arbex", 2013, "Geração Editorial", 3),
    ("Hamlet", "William Shakespeare", 1603, "L&PM", 4),
    ("Hibisco Roxo", "Chimamanda Ngozi Adichie", 2003, "Companhia das Letras", 2),
    ("Helena", "Machado de Assis", 1876, "Principis", 3),
    ("Homo Deus", "Yuval Noah Harari", 2015, "Companhia das Letras", 4),
    ("Hercule Poirot e o Mistério do Trem Azul", "Agatha Christie", 1928, "L&PM", 3),
    ("Heartstopper", "Alice Oseman", 2019, "Seguinte", 5),
    ("Hotel Paraíso", "Lucy Diamond", 2015, "Gutenberg", 2),
    # Letra I (10 livros)
    ("O Iluminado", "Stephen King", 1977, "Suma", 4),
    ("Inferno", "Dan Brown", 2013, "Arqueiro", 5),
    ("It: A Coisa", "Stephen King", 1986, "Suma", 3),
    ("Iracema", "José de Alencar", 1865, "Ática", 2),
    ("Ideias para Adiar o Fim do Mundo", "Ailton Krenak", 2019, "Companhia das Letras", 4),
    ("Imperador de Duna", "Frank Herbert", 1981, "Aleph", 3),
    ("A Interpretação dos Sonhos", "Sigmund Freud", 1899, "L&PM", 2),
    ("O Idiota", "Fiódor Dostoiévski", 1869, "Editora 34", 4),
    ("Indomada", "Glennon Doyle", 2020, "Sextante", 3),
    ("A Improvável Jornada de Harold Fry", "Rachel Joyce", 2012, "Suma", 2),
    # Letra J (10 livros)
    ("Jogos Vorazes", "Suzanne Collins", 2008, "Rocco", 5),
    ("Jantar Secreto", "Raphael Montes", 2016, "Companhia das Letras", 4),
    ("Jane Eyre", "Charlotte Brontë", 1847, "Zahar", 3),
    ("Jubiabá", "Jorge Amado", 1935, "Companhia das Letras", 2),
    ("A Jangada de Pedra", "José Saramago", 1986, "Companhia das Letras", 4),
    ("Jornada ao Centro da Terra", "Júlio Verne", 1864, "Principis", 3),
    ("Joyland", "Stephen King", 2013, "Suma", 2),
    ("Jogada de Mestre", "Harlan Coben", 2011, "Arqueiro", 4),
    ("Justiça", "Michael J. Sandel", 2009, "Civilização Brasileira", 3),
    ("Jardim de Inverno", "Kristin Hannah", 2010, "Arqueiro", 5),
    # Letra K (10 livros)
    ("Kafka à Beira-Mar", "Haruki Murakami", 2002, "Alfaguara", 3),
    ("Klara e o Sol", "Kazuo Ishiguro", 2021, "Companhia das Letras", 4),
    ("Kindred: Laços de Sangue", "Octavia E. Butler", 1979, "Morro Branco", 2),
    ("Kitchen", "Banana Yoshimoto", 1988, "Estação Liberdade", 3),
    ("O Kama Sutra", "Vatsyayana", 1883, "L&PM", 2),
    ("Kraken: A Armadilha", "China Miéville", 2010, "Boitempo", 3),
    ("Kairós", "Jenny Erpenbeck", 2021, "Record", 2),
    ("Karoshi", "Raphael Draccon", 2012, "Planeta", 4),
    ("O Kart Amarelo de Senna", "Lilian de Arruda", 2017, "Panda Books", 3),
    ("Kill Process", "William Hertling", 2016, "Aleph", 2),
    # Letra L (10 livros)
    ("Lua Nova", "Stephenie Meyer", 2006, "Intrínseca", 2),
    ("Laranja Mecânica", "Anthony Burgess", 1962, "Aleph", 4),
    ("Lucíola", "José de Alencar", 1862, "Martin Claret", 3),
    ("Lolita", "Vladimir Nabokov", 1955, "Alfaguara", 2),
    ("Lavoura Arcaica", "Raduan Nassar", 1975, "Companhia das Letras", 4),
    ("O Ladrão de Raios", "Rick Riordan", 2005, "Intrínseca", 5),
    ("Lady Killers", "Tori Telfer", 2017, "Darkside", 3),
    ("Lugar Nenhum", "Neil Gaiman", 1996, "Intrínseca", 4),
    ("A Longa Marcha", "Stephen King", 1979, "Suma", 2),
    ("Luzes do Norte", "Giulianna Domingues", 2021, "Galera", 3),
    # Letra M (10 livros)
    ("Memórias Póstumas de Brás Cubas", "Machado de Assis", 1881, "Antofágica", 5),
    ("O Morro dos Ventos Uivantes", "Emily Brontë", 1847, "Zahar", 4),
    ("Mentirosos", "E. Lockhart", 2014, "Seguinte", 3),
    ("Mindhunter", "John Douglas", 1995, "Intrínseca", 4),
    ("O Médico e o Monstro", "Robert Louis Stevenson", 1886, "L&PM", 2),
    ("Maus", "Art Spiegelman", 1980, "Companhia das Letras", 5),
    ("Mulheres que Correm com os Lobos", "Clarissa Pinkola Estés", 1992, "Rocco", 3),
    ("O Mágico de Oz", "L. Frank Baum", 1900, "Zahar", 4),
    ("Macunaíma", "Mário de Andrade", 1928, "L&PM", 2),
    ("O Milagre da Manhã", "Hal Elrod", 2012, "BestSeller", 5),
    # Letra N (10 livros)
    ("Neuromancer", "William Gibson", 1984, "Aleph", 3),
    ("Noites Brancas", "Fiódor Dostoiévski", 1848, "Editora 34", 4),
    ("Novembro de 63", "Stephen King", 2011, "Suma", 2),
    ("Nós", "Yevgeny Zamyatin", 1921, "Aleph", 3),
    ("Nunca me Abandone", "Kazuo Ishiguro", 2005, "Companhia das Letras", 4),
    ("Neve", "Orhan Pamuk", 2002, "Companhia das Letras", 2),
    ("Nada de Novo no Front", "Erich Maria Remarque", 1929, "L&PM", 3),
    ("Na Natureza Selvagem", "Jon Krakauer", 1996, "Companhia das Letras", 4),
    ("Niketche: Uma História de Poligamia", "Paulina Chiziane", 2002, "Companhia das Letras", 2),
    ("Nascido do Crime", "Trevor Noah", 2016, "Sextante", 5),
    # Letra O (10 livros)
    ("Orgulho e Preconceito", "Jane Austen", 1813, "Martin Claret", 5),
    ("O Pequeno Príncipe", "Antoine de Saint-Exupéry", 1943, "Agir", 5),
    ("Os Sete Maridos de Evelyn Hugo", "Taylor Jenkins Reid", 2017, "Paralela", 4),
    ("O Conto da Aia", "Margaret Atwood", 1985, "Rocco", 3),
    ("O Sol é para Todos", "Harper Lee", 1960, "José Olympio", 4),
    ("O Apanhador no Campo de Centeio", "J.D. Salinger", 1951, "Editora do Autor", 2),
    ("Outsider", "Stephen King", 2018, "Suma", 3),
    ("Origem", "Dan Brown", 2017, "Arqueiro", 5),
    ("Olhos d'Água", "Conceição Evaristo", 2014, "Pallas", 4),
    ("Objetos Cortantes", "Gillian Flynn", 2006, "Intrínseca", 2),
    # Letra P (10 livros)
    ("Ponto de Impacto", "Dan Brown", 2001, "Arqueiro", 4),
    ("Persépolis", "Marjane Satrapi", 2000, "Companhia das Letras", 3),
    ("Psicose", "Robert Bloch", 1959, "Darkside", 2),
    ("Pai Rico, Pai Pobre", "Robert T. Kiyosaki", 1997, "Alta Books", 5),
    ("Persuasão", "Jane Austen", 1817, "Zahar", 4),
    ("A Paciente Silenciosa", "Alex Michaelides", 2019, "Record", 3),
    ("O Poder do Hábito", "Charles Duhigg", 2012, "Objetiva", 5),
    ("Pessoas Normais", "Sally Rooney", 2018, "Companhia das Letras", 4),
    ("Ponciá Vicêncio", "Conceição Evaristo", 2003, "Pallas", 2),
    ("Para Todas as Pessoas Intensas", "Iandê Albuquerque", 2017, "Planeta", 3),
    # Letra Q (10 livros)
    ("Quarto de Despejo", "Carolina Maria de Jesus", 1960, "Ática", 4),
    ("Quincas Borba", "Machado de Assis", 1891, "Principis", 3),
    ("Quando a Neve Cai", "John Green", 2008, "Rocco", 2),
    ("Quem Pensa Enriquece", "Napoleon Hill", 1937, "Citadel", 5),
    ("Quem é Você, Alasca?", "John Green", 2005, "Intrínseca", 4),
    ("O Quinze", "Rachel de Queiroz", 1930, "José Olympio", 3),
    ("A Queda da Casa de Usher", "Edgar Allan Poe", 1839, "L&PM", 2),
    ("Qualquer Gato Vira-lata", "Juca de Oliveira", 1998, "Giostri", 4),
    ("O Que o Sol Faz com as Flores", "Rupi Kaur", 2017, "Planeta", 5),
    ("Queria que Você me Visse", "Penelope Douglas", 2014, "The Gift Box", 3),
    # Letra R (10 livros)
    ("A Revolução dos Bichos", "George Orwell", 1945, "Companhia das Letras", 5),
    ("Romeu e Julieta", "William Shakespeare", 1597, "L&PM", 4),
    ("Razão e Sensibilidade", "Jane Austen", 1811, "Zahar", 3),
    ("O Retrato de Dorian Gray", "Oscar Wilde", 1890, "Principis", 4),
    ("Rápido e Devagar", "Daniel Kahneman", 2011, "Objetiva", 2),
    ("A Rainha Vermelha", "Victoria Aveyard", 2015, "Seguinte", 5),
    ("Relato de um Náufrago", "Gabriel García Márquez", 1970, "Record", 3),
    ("Rita Lee: Uma Autobiografia", "Rita Lee", 2016, "Globo Livros", 4),
    ("Roube Como um Artista", "Austin Kleon", 2012, "Rocco", 2),
    ("Rangers: A Ordem dos Arqueiros", "John Flanagan", 2004, "Fundamento", 5),
    # Letra S (10 livros)
    ("O Senhor dos Anéis", "J.R.R. Tolkien", 1954, "HarperCollins", 5),
    ("Sapiens", "Yuval Noah Harari", 2011, "L&PM", 4),
    ("O Silmarillion", "J.R.R. Tolkien", 1977, "HarperCollins", 3),
    ("Senhora", "José de Alencar", 1875, "Ática", 2),
    ("O Símbolo Perdido", "Dan Brown", 2009, "Arqueiro", 4),
    ("Sol da Meia-Noite", "Stephenie Meyer", 2020, "Intrínseca", 5),
    ("A Seleção", "Kiera Cass", 2012, "Seguinte", 4),
    ("Sobre a Escrita", "Stephen King", 2000, "Suma", 2),
    ("Suicidas", "Raphael Montes", 2012, "Companhia das Letras", 3),
    ("Sutil Arte de Ligar o F*da-se", "Mark Manson", 2016, "Intrínseca", 5),
    # Letra T (10 livros)
    ("Torto Arado", "Itamar Vieira Junior", 2019, "Todavia", 5),
    ("O Teorema Katherine", "John Green", 2006, "Intrínseca", 3),
    ("Teto Para Dois", "Beth O'Leary", 2019, "Intrínseca", 4),
    ("Triste Fim de Policarpo Quaresma", "Lima Barreto", 1915, "L&PM", 2),
    ("Textos Cruéis Demais Para Serem Lidos Rapidamente", "Igor Pires", 2017, "Globo Alt", 4),
    ("Trono de Vidro", "Sarah J. Maas", 2012, "Galera", 5),
    ("A Tormenta de Espadas", "George R. R. Martin", 2000, "LeYa", 3),
    ("Tudo é Rio", "Carla Madeira", 2014, "Record", 2),
    ("Tartarugas Até Lá Embaixo", "John Green", 2017, "Intrínseca", 4),
    ("Terra Sonâmbula", "Mia Couto", 1992, "Companhia das Letras", 3),
    # Letra U (10 livros)
    ("Utopia", "Thomas More", 1516, "L&PM", 2),
    ("Úrsula", "Maria Firmina dos Reis", 1859, "Antofágica", 3),
    ("Um Conto de Duas Cidades", "Charles Dickens", 1859, "Zahar", 4),
    ("Uma Vida Pequena", "Hanya Yanagihara", 2015, "Record", 2),
    ("Um de Nós Está Mentindo", "Karen M. McManus", 2017, "Galera Record", 5),
    ("Uma Breve História do Tempo", "Stephen Hawking", 1988, "Intrínseca", 3),
    ("Um Estudo em Vermelho", "Arthur Conan Doyle", 1887, "Zahar", 4),
    ("Uma Mulher no Escuro", "Charlie Donlea", 2018, "Faro Editorial", 2),
    ("Última Parada", "Casey McQuiston", 2021, "Seguinte", 3),
    ("Um Amor para Recordar", "Nicholas Sparks", 1999, "Novo Conceito", 5),
    # Letra V (10 livros)
    ("Vidas Secas", "Graciliano Ramos", 1938, "Record", 5),
    ("Vinte Mil Léguas Submarinas", "Júlio Verne", 1870, "Principis", 3),
    ("Viagem ao Centro da Terra", "Júlio Verne", 1864, "Zahar", 4),
    ("Vermelho, Branco e Sangue Azul", "Casey McQuiston", 2019, "Seguinte", 5),
    ("Verity", "Colleen Hoover", 2018, "Galera Record", 3),
    ("A Vida Invisível de Addie LaRue", "V.E. Schwab", 2020, "Galera", 4),
    ("Vigiar e Punir", "Michel Foucault", 1975, "Vozes", 2),
    ("A Vegetariana", "Han Kang", 2007, "Todavia", 3),
    ("A Visita Cruel do Tempo", "Jennifer Egan", 2010, "Intrínseca", 2),
    ("V de Vingança", "Alan Moore", 1982, "Panini", 4),
    # Letra W (10 livros)
    ("Walden", "Henry David Thoreau", 1854, "L&PM", 2),
    ("Warcross", "Marie Lu", 2017, "Rocco", 4),
    ("Wildcard", "Marie Lu", 2018, "Rocco", 3),
    ("Watchmen", "Alan Moore", 1986, "Panini", 5),
    ("Winter", "Marissa Meyer", 2015, "Rocco", 3),
    ("Will & Will", "John Green & David Levithan", 2010, "Galera Record", 4),
    ("Wonder Woman: Sementes da Terra", "G. Willow Wilson", 2019, "Panini", 2),
    ("Wytches", "Scott Snyder", 2014, "Darkside", 3),
    ("Wolfsong: O Chamado", "TJ Klune", 2016, "Plataforma21", 4),
    ("Wicca: A Religião da Deusa", "Claudiney Prieto", 2000, "Alfabeto", 2),
# Letra X (10 livros)
    ("Xógum", "James Clavell", 1975, "Record", 4),
    ("Xisto", "Fernando Pessoa", 1934, "Ática", 2),
    ("Xadrez dos Loucos", "David Gerrold", 1977, "Suma", 3),
    ("X-Men: Deus Ama, o Homem Mata", "Chris Claremont", 1982, "Panini", 5),
    ("Xerloque Holmes: O Cão dos Baskervilles", "Arthur Conan Doyle", 1902, "Principis", 4),
    ("Xica da Silva", "Agripa Vasconcelos", 1976, "Garnier", 2),
    ("Xenogênese", "Octavia E. Butler", 1987, "Morro Branco", 3),
    ("X-O Manowar", "Jim Shooter", 1992, "Jambô", 4),
    ("Xalingo, o Rei do Xingu", "Lia Zatz", 2005, "Moderna", 2),
    ("Xingu: O Velho e o Moço", "Aida Rameh de Siqueira", 2011, "Paz e Terra", 3),
    # Letra Y (10 livros)
    ("Y: O Último Homem", "Brian K. Vaughan", 2002, "Panini", 5),
    ("Yasmin", "Matthew Hussein Ayoub", 2008, "Companhia das Letras", 2),
    ("Yoga para Nervosos", "José Hermógenes", 1960, "BestSeller", 4),
    ("Yesterday", "Juan Emar", 1935, "Rocco", 2),
    ("Your Name.", "Makoto Shinkai", 2016, "JBC", 5),
    ("Yara", "Frederico Valois", 2019, "Penalux", 2),
    ("Yankee", "Mark Twain", 1889, "Zahar", 3),
    ("Yôga: Sútras de Pátañjali", "Pátañjali", 200, "Mantra", 3),
    ("O YIN e o YANG da Nutrição", "Cláudio D. V. Lopes", 2015, "Vozes", 2),
    ("Yellowface", "R.F. Kuang", 2023, "Intrínseca", 4),
    # Letra Z (10 livros)
    ("Assim Falou Zaratustra", "Friedrich Nietzsche", 1883, "Companhia das Letras", 5),
    ("Zazie no Metrô", "Raymond Queneau", 1959, "L&PM", 3),
    ("Zodíaco", "Romina Russell", 2014, "Rocco", 4),
    ("Zumbis x Unicórnios", "Holly Black", 2010, "Galera Record", 3),
    ("Z de Zumbi", "Max Brooks", 2006, "Rocco", 4),
    ("Zona Morta", "Stephen King", 1979, "Suma", 5),
    ("Zoológico de Gelo", "Don DeLillo", 1997, "Companhia das Letras", 2),
    ("Zero à Esquerda", "Ignácio de Loyola Brandão", 1981, "Global Editora", 3),
    ("Zorro: O Começo da Lenda", "Isabel Allende", 2005, "Bertrand Brasil", 4),
    ("Zafón: O Príncipe da Névoa", "Carlos Ruiz Zafón", 1993, "Suma", 5),
]